logging:
  config: classpath:log4j2-dev.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlite::resource:portscanner.db

server:
  port: 8080
  servlet:
    session:
      cookie:
        max-age: -1